### ISSUE TITLE
不支持新的IDEA社区版，不支持@FeignClient path属性

### ISSUE THREAD

**Issue by ABoat365** [pxpy/jump-to-controller#2]
虽然新的IDEA社区版可以安装，但可能是org.jetbrains.intellij插件太老，有些报错。另外不支持@FeignClient path属性，只能在feign接口上写完整路径。JavaSourceFileUtil类中的extractControllerInfo方法，parentPath属性在Controller2Feign或Feign2Controller中都是传入空值，导致@FeignClient path属性有值的接口无法找到并跳转。

**Comment by pxpy** [comment]
已添加@FeignClient path属性支持
